pipeline {
    agent {
        docker {
            image 'gradle:8.4-jdk17'   // Usa imagem do Gradle com JDK 17 pronto
            args '-v /var/run/docker.sock:/var/run/docker.sock'
        }
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/LeonardoTonon1234/catalogo-filmes-aws-Final.git'
            }
        }

        stage('Build') {
            steps {
                dir('backend') {
                    echo 'Executando build do projeto com Gradle + JDK 17...'
                    sh './gradlew clean build -x test'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('backend') {
                    echo 'Construindo imagem Docker...'
                    sh 'docker build -t catalogo-filmes .'
                }
            }
        }

        stage('Run Container') {
            steps {
                echo 'Executando container do catálogo de filmes...'
                sh 'docker run -d -p 8082:8080 --name catalogo-filmes catalogo-filmes || true'
            }
        }
    }
}

