pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/LeonardoTonon1234/catalogo-filmes-aws-Final.git'
            }
        }

        stage('Build com Gradle') {
            steps {
                dir('backend') {
                    echo '🔧 Executando build do projeto com Gradle + JDK 17...'
                    sh './gradlew clean build -x test'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('backend') {
                    echo '🐳 Construindo imagem Docker...'
                    sh 'docker build -t catalogo-filmes .'
                }
            }
        }

        stage('Run Container') {
            steps {
                echo '🚀 Executando container do catálogo de filmes...'
                sh '''
                    docker stop catalogo-filmes || true
                    docker rm catalogo-filmes || true
                    docker run -d -p 8080:8080 --name catalogo-filmes catalogo-filmes
                '''
            }
        }
    }
}

